name: AgriConnect CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17 for Android
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android_app

    - name: Build Android App
      run: ./gradlew build
      working-directory: android_app

    - name: Run Android Unit Tests
      run: ./gradlew testDebugUnitTest
      working-directory: android_app

    - name: Run Android Instrumentation Tests (Placeholder - Requires Emulator/Device)
      run: |
        echo "Skipping connectedDebugAndroidTest: Requires emulator setup."
      # To enable, you would use a command like:
      # ./gradlew connectedDebugAndroidTest
      # And potentially an action to set up an emulator, e.g., reactivecircus/android-emulator-runner
      working-directory: android_app

    - name: Set up Deno for Supabase Edge Functions
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x # Specify your Deno version

    - name: Test Supabase Edge Functions
      run: deno test --allow-all index.test.ts
      working-directory: supabase/functions/user-profile-init
      # Adjust --allow-all with specific permissions if preferred